name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            👋 Hello and welcome to the project, @${{ github.actor }}!

            Thank you for opening your first issue. We’ll review it soon.  
            Make sure to check our contribution guidelines in the README.  
            We’re happy to have you here 🚀
          
          pr-message: >
            🎉 Hey @${{ github.actor }}, thanks for your first pull request!

            We really appreciate your effort in contributing.  
            One of the maintainers will review your PR shortly.  
            Keep up the great work! 💪
